directories:
  output: dist-electron
  buildResources: build
appId: com.doctorpc.stock
productName: Doctor PC Stock
copyright: Copyright © 2024
asar: false
win:
  target: nsis
  icon: dist/doctorpc-stock/browser/assets/logo.ico
publish:
  - provider: github
    owner: kevin2561
    repo: sistema-doctor-pc
files: []
electronVersion: 35.0.1
